### ISSUE TITLE
Possibility for multiple sensor connect?

### ISSUE THREAD

**Issue by deadeyesky** [dzheng256/adxl345spi-py#1]
I know this is probably mundane and forgive me if I don't understand, but is there a way to use this program with multiple ADXL345 sensors?

**Comment by dzheng256** [comment]
Hmm that's not explicitly supported by this program and depends more on the SPI interface as well as how many sensors you can connect to your raspberry pi.

**Comment by deadeyesky** [comment]
Do you know if there is a way that I can read from two different sensors? I just think this program would be even more powerful if it could be operated with multiple adxl345s. In my case, I only want to read from two. Or maybe if it is better since Python is slower than C++, to add multiple sensor capabilities to the C version of this script from https://github.com/nagimov/adxl345spi

**Comment by dzheng256** [comment]
I don't know off the top of my head, but I'm sure it's possible. I believe SPI supports multiple slave devices? If you figure it out, feel free to submit a PR
